### ISSUE TITLE
manim installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by nioate** [3b1b/manim#1004]
I am trying to install manimlib on Ubuntu 20.04, following [https://manim.readthedocs.io/en/latest/installation/linux.html](https://manim.readthedocs.io/en/latest/installation/linux.html)
```
$ pip3 install manimlib
...
ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.2.17 (from manimlib) (from versions: 3.4.8.29, 3.4.9.31, 3.4.9.33, 4.1.2.30, 4.2.0.32, 4.2.0.34)
ERROR: No matching distribution found for opencv-python==3.4.2.17 (from manimlib)
```
I also tried
```
$ sudo pip3 install opencv-python
...
Successfully installed numpy-1.18.3 opencv-python-4.2.0.34
```
but still the same error. Any suggestion what is missing or wrong?

**Comment by zavden** [comment]
That's because your python version is 3.8, the open-cv version that manimlib uses is 3.4, so you should use `python3.7 -m pip install manimlib`.
In case you don't want to install Python 3.7 and use 3.8 you can use [this](https://www.youtube.com/watch?v=z_WJaHYH66M&list=PL2B6OzTsMUrwo4hA3BBfS7ZR34K361Z8F&index=4) tutorial. Change the [requieriments.txt](https://github.com/3b1b/manim/blob/3b088b12843b7a4459fe71eba96b70edafb7aa78/requirements.txt#L8) file with this:

```
argparse==1.4.0
colour==0.1.5
numpy==1.15.0
Pillow==5.2.0
progressbar==2.5
scipy==1.1.0
tqdm==4.24.0
opencv-python
pycairo
pydub
```

**Comment by nioate** [comment]
Thanks, zavden!
There were still some incompatible versions (e.g. numpy-1.15.0 didn't work with opencv-python-4.2.0.34), so I uninstalled some of the packages again, in the end I removed all version numbers in the requirements.txt and then it worked.

**Comment by zavden** [comment]
Perfect, then close the issue please.
