### ISSUE TITLE
Preview option from extract_scene

### ISSUE THREAD

**Issue by frozar** [3b1b/manim#103]
In the current file `extract_scene.py`, the preview option seems to be inefficient. When I check the script, it seems to have no effect at all in the configuration variable.

Is it possible to get back this feature please?

**Comment by bhbr** [comment]
Have you used the -l (low quality) flag?

**Comment by frozar** [comment]
On the current master branch, I used this command:
```
$ python extract_scene.py example_scenes.py SquareToCircle -l
```

It generates a low quality video quickly, that's fine.  What I was talking about is a previous feature which allows to preview the generated video in a small tk window. It was removed in january (I think). It was useful to quickly check a result of a command.

If it's not possible to get back this feature, I will survive with `-l` option.

**Comment by bhbr** [comment]
Use -pl and it will automatically open the rendered file. This is just as quick as a tk window.

**Comment by 3b1b** [comment]
It's worth mention that this relies on the "open" command, which may just be a unix thing.  I'm not positive that would work on windows, but if not, I'm sure it's a simple fix to make it more general.   If that were the case, pull requests are welcomed :)

I removed the tk window because, at least when this works, it dominates the functionality of the previous previewing method, with all the added niceties that your systems media player offers.

**Comment by frozar** [comment]
Ok, I proposed a MR for this Issue. You were right, the bug was using the `open` program. So I fixed it for Linux platform but as I don't have a Windows machine to test it, under Windows the `open` is still used (and maybe fail). By the way with the tiny modifications I proposed, things should be better :cat:
