### ISSUE TITLE
Cannot set different color in specific Tex forms.

### ISSUE THREAD

**Issue by JimChr-R4GN4R** [3b1b/manim#1121]
Let's say I have:
```
        p_calc = TexMobject("p","=",r"\frac{n}{q}")
        p_calc.set_color_by_tex_to_color_map({
            "n": RED,
            "p": BLUE,
            "q": GREEN
        })
```
which `p_calc ` is `p=n/q`.

I want p to be blue colored,n red colored and q green colored.

I have tried different methods,even `\frac{{\color{Red} a}}{b}` but still it changes all `n/q` to color green or is not acceptable.

**Comment by PackSciences** [comment]
frac has two arguments, you can't color it with Manim unfortunately (I too complain about that don't worry).

An alternative is to use \over : 
`x = TexMobject("a", "+", "{2", r"\over", "3}")`

**Comment by JimChr-R4GN4R** [comment]
Thank you!

So if anyone has a similar problem,just do this:
```
x = TexMobject("a", "+", "{n", "\\over", "q}")
x.set_color_by_tex("n", YELLOW).set_color_by_tex("q", RED)
```

or this:

```
x = TexMobject("a", "+", "{q", "\\over", "n}")
x.set_color_by_tex_to_color_map({
     "n": YELLOW,
     "q": RED
})
```

**Comment by Tony031218** [comment]
```python
t2c = {"n": YELLOW, "q": RED}
text = TexMobject("a+{n \\over q}", tex_to_color_map=t2c)
```
@JimChr-R4GN4R This is also feasible.
This is because when initializing `TexMobject`, the incoming `tex_to_color_map` will automatically split the incoming string according to the keys in the t2c dictionary. However, the string cannot be automatically split when using the `set_color_by_tex_to_color_map` method after initialization.
