### ISSUE TITLE
Error al animar texto (dvisvgm se queda sin terminar su tarea)

### ISSUE THREAD

**Issue by carloskl12** [3b1b/manim#1181]
Estoy en un entorno de anaconda con todos lo necesario para correr manim, generar animaciones con gráficos sin texto funciona bien, pero para el texto se queda congelado el proceso, esto ocurre cuando trato de ejecutar uno de los ejemplos:

1. Steps to reproduce the issue: > python build.py example_scenes.py WriteStuff -pl
2. The unexpected behavior that occurred: >> ... se queda sin terminar la tarea de dvisvgm
3. The environment: Ubuntu 16, utilizando anaconda, y la última versión disponible

Tenía una versión anterior de Manim que si funcionaba, entonces luego de muchas pruebas noté que en el template de latex al utilizar usepackage[T1]{fontenc} genera un dvi que la versión 1.9.2 de dvisvgm no puede terminar de procesar, entonces comenté esa línea y me funcionó.

Escribo esto por si alguien tiene el mismo problema.

**Comment by Jaime02** [comment]
@carloskl12 permíteme traducir al inglés tu problema para que pueda comprenderlo todo el mundo.

I am in an anaconda environment with everything requiered to run manim, Generating animations with graphics works properly, but text stays frozen during process. This happens when I try to run some of the examples:

    1. Steps to reproduce the issue: > python build.py example_scenes.py WriteStuff -pl
    2. The unexpected behavior that occurred: >> the task dvisvgm does not end
    3. The environment: Ubuntu 16, using anaconda, last version avaiable.

I had the previous version of Manim which worked fine. After many tests, I noticed that the latex's template which uses usepackage[T1]{fontenc} generates a dvi at version 1.9.2, which dvisvgm can not process. Then, I commented in that line and it worked.
I write this text in case someone has the same problem.
