### ISSUE TITLE
pip3 does not install manim.py script

### ISSUE THREAD

**Issue by bth5032** [3b1b/manim#1185]
Hi, this is a small bug, but the documentation in the README says that after a `pip3 install manimlib` the `manim` command will be available. I just installed this tonight and it didn't make that command available to me, and `python3 -m manim` threw an error saying the module was not found.

I managed to get this to work by cloning the repo and running manim.py from the code there, but this is pretty non-standard for pip installation and I didn't see it mentioned anywhere in the docs that you need to do this. 

It might be an issue with pip, but just thought I'd leave this here incase anyone else gets hit by this issue.

Best!

**Comment by suhailsherif** [comment]
I had a similar problem when I installed it (on Ubuntu). It turned out that the pip3 installs were installed in `/home/suhail/.local/bin`, and this was not in my PATH.

Adding `export PATH=$PATH:/home/suhail/.local/bin` to my .bashrc file and restarting the terminal did the trick. Even other commands like pip started working.

**Comment by bth5032** [comment]
Thanks this is the answer, I shake my fist at non-standard ubuntu pathing

**Comment by pranav381** [comment]
I have some trouble with the cmd python3.7 get-pip.py. after entering this cmd I can only see pip installing however, in the video tutorial for installing manim the same cmd also collecting setuptools and wheel. 
![Screenshot_2020-08-02_18-44-06](https://user-images.githubusercontent.com/47829488/89123866-2ff44a80-d4f0-11ea-89de-5d6feb822e03.png)
