### ISSUE TITLE
Error with PIL?

### ISSUE THREAD

**Issue by SMoctezuma** [3b1b/manim#12]
Hello, I tried running the command 'python extract_scene.py -p example_scenes.py SquareToCircle' as instructed. I have install all requirements and the project looks fine and all. But in console, I'm getting this error, could someone enlightening me on this problem.

Stevens-MacBook-Pro:manim Steven$ python extract_scene.py -p example_scenes.py SquareToCircle

Traceback (most recent call last):
  File "extract_scene.py", line 173, in main
    handle_scene(SceneClass(**scene_kwargs), **config)
  File "/Users/Steven/PycharmProjects/manim/scene/scene.py", line 36, in __init__
    self.construct(*self.construct_args)
  File "/Users/Steven/PycharmProjects/manim/./example_scenes.py", line 34, in construct
    self.play(ShowCreation(square))
  File "/Users/Steven/PycharmProjects/manim/scene/scene.py", line 240, in play
    self.update_frame(static_mobjects)
  File "/Users/Steven/PycharmProjects/manim/scene/scene.py", line 70, in update_frame
    self.camera.capture_mobjects(mobjects, **kwargs)
  File "/Users/Steven/PycharmProjects/manim/camera.py", line 84, in capture_mobjects
    canvas = aggdraw.Draw(image)
  File "/Users/Steven/Library/Python/2.7/lib/python/site-packages/PIL/Image.py", line 510, in __getattr__
    raise AttributeError(name)
AttributeError: tobytes

sh: play: command not found

I've reviewed the code over and over again but maybe I'm just not understanding the process behind it. But I'm at a loss, any help would be much appreciated.

**Comment by 3b1b** [comment]
I think this problem comes about if you use a too-recent version of PIL.  For whatever reason, aggdraw only seems to work with Pillow==1.7.8.  Does that help?

**Comment by GreatNoyz** [comment]
Thanks for responding, and I am using Pillow 1.7.8. At first I was using python 3.4 but I noticed that I was getting error in dependencies because I had Pillow 3.4.2 which is the latest (I think). So I had to switch to python 2.7 because Pillow 1.7.8 doesn't support the newest python version. I was up all last night trying to get python setup, (I am a java programmer so this environment is a bit new to me) and I kept getting an error on installing Pillow 1.7.8 on python 2.7 but it turns out there was an issue with x-code so I had to install other pre-requisites which just prolonged the setup process. Just f.y.i. I'm using PyCharm IDE, if that helps you out in any way. 

<img width="1240" alt="screen shot 2016-11-07 at 2 58 43 pm" src="https://cloud.githubusercontent.com/assets/3750077/20075655/bdb08cf0-a4fa-11e6-9853-64520b3bccac.png">

**Comment by dystricht** [comment]
I am also stuck on this same issue. Will post more info and my workaround momentarily.

**Comment by GreatNoyz** [comment]
Okay thanks, I'm still stuck on this so any insight on this situation will be much appreciated!

**Comment by GreatNoyz** [comment]
Okay so I narrowed down to where the problem lies but I don't really know how to fix it. In scenes.py, line 70, if you comment out the statement "self.camera.capture_mobjects(mobjects, **kwargs)" the program will run flawlessly. However that statement is what draws the images to the scene I believe. So it doesn't display anything except the "playground". What i've deduced is that possibly the method in camera called capture_mobjects is passing the wrong data type? Because in camera.py, line 84, is where the error begins. So is it possible aggdraw.Draw() is expecting another member?

**Comment by CrypticSwarm** [comment]
I was able to get past the issue which appears to be the same as the one here: (https://github.com/python-pillow/Pillow/issues/2190) 

When using python 2.7 you the `tobytes` does not exist, and errors out if you installed aggdraw using the  repo linked in the `README` at the `master` branch. 

I was able to get the example to run (preview only displayed a black box, but the video `-w` command generated correctly) by installing aggdraw from this commit (https://github.com/scottopell/aggdraw-64bits/commit/dd17951112d70851346d1216ad015e2051163e60) rather than `master`.

```
git clone https://github.com/scottopell/aggdraw-64bits
cd aggdraw-64bits
git checkout dd17951112d70851346d1216ad015e2051163e60
```

Then continuing with the rest of the install.

The problematic commit is: (https://github.com/scottopell/aggdraw-64bits/commit/9b69b6baa0c16d73bdca7fbb896523cfea858e81) which converts to `tostring` to `tobytes` for more recent versions of Pillow.

**Comment by CrypticSwarm** [comment]
This mismatch between aggdraw and Pillow seems to be at the root of this comment (https://github.com/3b1b/manim/issues/6#issuecomment-243012810).

>  For this specific issue, aggdraw for some reason only works with an older version of PIL, so uninstall Pillow, then reinstall with "pip install Pillow==1.7.8".

Everything seems to run smoothly when using `Pillow==3.4.2` and building/installing from the current HEAD of the master branch in the aggdraw repo:  (https://github.com/scottopell/aggdraw-64bits/commit/c95aac4369038706943fd0effb7d888683860e5a).

**Comment by eulertour** [comment]
Closing, since this issue is old and inactive.
