### ISSUE TITLE
A bug of apply_points_function in shaders branch

### ISSUE THREAD

**Issue by Tony031218** [3b1b/manim#1314]
In https://github.com/3b1b/manim/commit/f90e4147b6002a970adcb1afef793a280580468e, I found that `apply_points_function` has been changed a lot, one of which even caused OpeningManimExample to fail to run.

Note here:

https://github.com/3b1b/manim/blob/7b67f4556b631334cbb61f9c5bb5428befe1ba3b/manimlib/mobject/mobject.py#L144-L156

`mob` is all family objects, but for `NumberPlane` and `VGroup`, the first family object is itself, but it does not contain points, that is, `arrs` is an empty array. So the following error will be generated:

```python
  File "...\manimlib\scene\scene.py", line 378, in wrapper
    func(self, *args, **kwargs)
  File "...\manimlib\scene\scene.py", line 441, in play
    self.begin_animations(animations)
  File "...\manimlib\scene\scene.py", line 401, in begin_animations
    animation.begin()
  File "...\manimlib\animation\transform.py", line 43, in begin
    self.target_mobject = self.create_target()
  File "...\manimlib\animation\transform.py", line 185, in create_target
    method.__func__(target, *args, **method_kwargs)
  File "...\manimlib\mobject\types\vectorized_mobject.py", line 463, in apply_function
    Mobject.apply_function(self, function)
  File "...\manimlib\mobject\mobject.py", line 513, in apply_function
    **kwargs
  File "...\manimlib\mobject\mobject.py", line 156, in apply_points_function
    arr[:] = func(arr - about_point) + about_point
ValueError: operands could not be broadcast together with shapes (0,) (3,)
```

But I have tried to change the `get_family` of 
https://github.com/3b1b/manim/blob/7b67f4556b631334cbb61f9c5bb5428befe1ba3b/manimlib/mobject/mobject.py#L148
to `family_members_with_points`, but this will cause more serious problems. For example, `Integer` cannot even display correctly:
```python
self.add(Integer(10))
```
![image](https://user-images.githubusercontent.com/44120331/104733106-2f3b3200-5779-11eb-83a3-518e20c41bc3.png)

So how to fix this bug, @3b1b please consider about it :D

**Comment by 3b1b** [comment]
Thanks for pointing this out, this commit should fix it: https://github.com/3b1b/manim/commit/08e22cf8596d7a077669263d0af25026de96d9e2

The reason for the change has to do with a certain performance improvement.  Previously, simple methods like Mobject.get_center and Mobject.get_corner have been more computationally expensive than they should be, which in turn affects things like scale, rotate, move_to, shift, etc.  This is because each of those calls would involve finding the bounding box around the Mobject, which is a computation over all the points in the family hierarchy.  So instead, recent changes have the bounding box only recomputed when it needs to be, and for certain functions like scale/stretch/shift, these are applied directly to the bounding box rather than triggering a recomputation.

So if you're curious, while you're instinct to change get_family to get_family_with_points was right on, the reason it didn't work is that now if something like Mobject.scale is applied, it actually _does_ need to be applied to mobjects without points, in that it needs to hit their bounding box.

**Comment by Tony031218** [comment]
Got it! This is really a good idea.
