### ISSUE TITLE
error: unrecognized arguments: -pl

### ISSUE THREAD

**Issue by ali-lari** [3b1b/manim#1361]
After installing manim and trying to run the starter examples, I get the following error shown below.
![image](https://user-images.githubusercontent.com/62142578/107112734-35519980-6873-11eb-8cab-b8ac798903d3.png)

When I run the starter example without -pl, I get a Python animation (similar to what you'd get using the `Turtle` module) instead of an MP4 video? What is going on here?

Edit: the following is what happens when I run the command without -pl
![image](https://user-images.githubusercontent.com/62142578/107112780-a42ef280-6873-11eb-8f1b-4b02430907cd.png)

**Comment by abhi-6988** [comment]
@ali-lari In order to write to a file, you have to use the `-w` flag with current `master` (`-p` works only in the `cairo-backend` branch). And to open the rendered file, use `-o` flag. So your command would be `python manim.py example_scenes.py OpeningManimExample -wlo` (`-wlo` meaning write to a file in low quality and open it once rendered)
Run `python -m manim --help` to have a look at all the flags and their purpose.
