### ISSUE TITLE
how to use this source?

### ISSUE THREAD

**Issue by onloner2012** [3b1b/manim#14]
i'm a student,watch your video on youtube ,in the video,i know this source ,but ,today ,i use this source on python 3.xx,it's error,sorry ,my english is poor ,so ,you can tell me how to use this source? i really want to use this,thx

**Comment by sramsay64** [comment]
Try using python 2. I'm using Ubuntu 16.04 and I can run `python extract_scene.py eoc/chapter1.py OpeningQuote`. You write your videos as python classes in a python file and compile them to a video with that command. The command looks in eoc/chapter1.py and uses the `OpeningQuote` class. Take a look at the code for that class to get an Idea for making you own and try making a copy of it to play around with and modify. At least that's what I've been doing. One problem you might run into is that any video with a Pi creature in it can't be compiled because the Pi creature SVG file isn't included in this repo (understandably because that's more or less the trademark of 3b1b and Grant would want to keep the copyright). Good luck.

**Comment by onloner2012** [comment]
thinks for your help,i use Notebook on x86 structure,so it's not good fo Ubuntu ,so i have to use Win10,now i change to python 2.if hava some questions,can i ask help for you?In addition ,your math video is very very great than my teacher my text book ,in my country,you video is wide popularity,you maybe not think that,i watch translation video on  a anime website,hahaha,but,i watch your channel not update,because of your job?i know your information on Internet.they say:you resign your job , and make math video full time,in that way,You see what life? can these video Bring you benefits?

**Comment by TPVasconcelos** [comment]
I recommend closing this issue.
