### ISSUE TITLE
Using MObject.become method within a updater results in a loss of reference to the screen object.

### ISSUE THREAD

**Issue by michaelnicol** [3b1b/manim#1956]
Consider the following example:

```
class Example(Scene):
    def construct(self):
        rateOfChange = ValueTracker(1.00)
        def generateText():
            return MathTex(rateOfChange.get_value())
        currentText = generateText()
        self.play(Create(currentText))
        currentText.add_updater(lambda m : m.become(generateText()))
        self.play(rateOfChange.animate.set_value(2.00))
        self.play(currentText.animate.shift(LEFT*3))
        self.wait(1)
```
Here, a value tracker is used to animate between the values 0 and 1.

The text on the screen transitions to a new MathTex object each frame using the ```become``` method.

However, at the end of the update animation, the:

```
currentText.animate.shift(LEFT*3)
```
No longer works because the ```currentText``` variable no longer references the new objects created in each frame.

**Comment by 3b1b** [comment]
I think this is meant for the [ManimCommunity repo](https://github.com/manimCommunity/manim).

This particular issue is not because of Mobject.become, when generateText returns an object, it's always creating a new one that is centered. So as the updater continues to work, it overrides the animation attempting to shift the item to the left.  You can tell because calling `currentText.clear_updaters()` before the shift will make it work.

Also, for what it's worth, this particular animation would be better accomplished (and runs much, much faster) using a DecimalNumber and the ChangeDecimalToValue animation.

```
class Example(InteractiveScene):
    def construct(self):
        currentText = DecimalNumber(1.0)
        self.play(ChangeDecimalToValue(currentText, 2))
```
