### ISSUE TITLE
Issue with graphing

### ISSUE THREAD

**Issue by ItsPlantseed** [3b1b/manim#302]
Whenever I tried 1/x or 1/(x^2-4) (as shown in the picture). It comes up with something weird, almost distorted near the asymptote. Am I missing something? [attached file](http://imgur.com/a/AGl4foQ).

**Comment by DanWaxman** [comment]
To explain why your graph looks specifically like that, manim takes a number of anchor points, evaluates the function at those anchor points, then connects them. The default number of anchor points is quite low for a larger domain at 50. You can change your config adding in "num_graph_anchor_points" to change this a bit.

However, due to the same reasoning as above, you still will end up with messed up asymptotes. The only way I know how to fix this is to graph separately over each interval of the domain of the function. There might be a more elegant way around this, but it seems like [Grant used this in a past project](https://github.com/3b1b/manim/blob/fa37c8b1d41c438cd5e064318416797330fa162b/old_projects/eoc/chapter6.py#L1873) so I don't think there is one at the current time.

**Comment by ItsPlantseed** [comment]
Thank you. I guess there is no other way, it's indeed not very convenient. But I wouldn't say that it was intentional.
