### ISSUE TITLE
Continual update stops when doing another play command

### ISSUE THREAD

**Issue by BjornFidder** [3b1b/manim#332]
I'm animating a bouncing ball and I'm using the continual update function to accomplish this. While this continual update is running, I'd like to display some text on the screen. However, while a play command is running, the ball freezes for a moment. When the play command is over, the ball jumps to where it is supposed to be and continues moving. 
I'd like to know if there is a way to keep the continual update working while running another animation.

**Comment by eulertour** [comment]
Can you paste the problem Scene, or a minified version of it?

**Comment by BjornFidder** [comment]
[bouncing_ball.pdf](https://github.com/3b1b/manim/files/2514082/bouncing_ball.pdf)

Included a pdf of my code. The problem arises when fading in and transforming text1 and text2. The ball temporarily stops moving.

**Comment by eulertour** [comment]
Apologies for the delay. The problem here is that you're hacking the internals of the `Scene` class by overriding `continual_update()` rather than letting it handle the continual animation for you. The relevant codepath is here:

1. [`continual_update()` is called on every frame of the animation](https://github.com/3b1b/manim/blob/31478c523c9febb85d673219c6451ce545b5e319/scene/scene.py#L479)
2. [`continual_update()` calls `update()` on each Mobject and ContinualAnimation which has been added to the `Scene`](https://github.com/3b1b/manim/blob/31478c523c9febb85d673219c6451ce545b5e319/scene/scene.py#L175)
3. [`update()` does some bookkeeping and then calls `update_mobject()` on itself](https://github.com/3b1b/manim/blob/31478c523c9febb85d673219c6451ce545b5e319/continual_animation/continual_animation.py#L35)

This means you can continually update `ball` by creating a `ContinualAnimation`, passing `ball` to it, and overriding its `update_mobject()` method to update the ball every frame. That will look something like this:

```python
from big_ol_pile_of_manim_imports import *


class Ball(Circle):
    CONFIG = {
        "radius": 0.4,
        "fill_color": BLUE,
        "fill_opacity": 1,
        "color": BLUE
    }

    def __init__(self, ** kwargs):
        Circle.__init__(self, ** kwargs)
        self.velocity = np.array((2, 0, 0))

    def get_top(self):
        return self.get_center()[1] + self.radius

    def get_bottom(self):
        return self.get_center()[1] - self.radius

    def get_right_edge(self):
        return self.get_center()[0] + self.radius

    def get_left_edge(self):
        return self.get_center()[0] - self.radius


class Box(Rectangle):
    CONFIG = {
        "height": 6,
        "width": FRAME_WIDTH - 2,
        "color": GREEN_C
    }

    def __init__(self, ** kwargs):
        Rectangle.__init__(self, ** kwargs)  # Edges
        self.top = 0.5 * self.height
        self.bottom = -0.5 * self.height
        self.right_edge = 0.5 * self.width
        self.left_edge = -0.5 * self.width


class ContinualBallUpdate(ContinualAnimation):
    def __init__(self, ball, box):
        self.ball = ball
        self.box = box
        ContinualAnimation.__init__(self, ball)

    def update_mobject(self, dt):
        self.ball.acceleration = np.array((0, -5, 0))
        self.ball.velocity = self.ball.velocity + self.ball.acceleration * dt
        self.ball.shift(self.ball.velocity * dt)  # Bounce off ground and roof
        if self.ball.get_bottom() <= self.box.bottom or \
                self.ball.get_top() >= self.box.top:
            self.ball.velocity[1] = -self.ball.velocity[1]

        # Bounce off walls
        if self.ball.get_left_edge() <= self.box.left_edge or \
                self.ball.get_right_edge() >= self.box.right_edge:
            self.ball.velocity[0] = -self.ball.velocity[0]


class Bouncing_Ball(Scene):
    def construct(self):

        self.box = Box()

        ball = Ball()

        self.play(FadeIn(self.box))
        self.play(FadeIn(ball))
        self.ball = ball

        self.add(ContinualBallUpdate(ball, self.box))
        text1 = TextMobject("This is a bouncing ball")
        text2 = TextMobject("Enjoy watching!")
        self.wait(1)
        self.play(FadeIn(text1))

        self.wait(2)
        self.play(Transform(text1, text2))

        self.wait(10)
```

And render to this.
![bouncing ball](https://thumbs.gfycat.com/ElaborateCourteousFlyingfish-size_restricted.gif)

**Comment by Momopey** [comment]
The continualAnimation class no longer exists
