### ISSUE TITLE
Recommendation to enable Transform(m1,m2).update(1)

### ISSUE THREAD

**Issue by Elteoremadebeethoven** [3b1b/manim#491]
I think the command ```Transform(mobject1, mobject2).update(1)``` when we use ```def update(group,alpha)``` is very useful. In this version is disabled, but if the next files have a little changes then works:
manimlib/animation/animation.py
```python3
    def __init__(self, mobject, **kwargs):
        assert(isinstance(mobject, Mobject))
        digest_config(self, kwargs)
        self.mobject = mobject
        self.starting_mobject = self.create_starting_mobject() # Add this line in 34

    def __str__(self):
        if self.name:
            return self.name
        return self.__class__.__name__ + str(self.mobject)
```
manimlib/animation/transform.py
```python3
    def __init__(self, mobject, target_mobject=None, **kwargs):
        super().__init__(mobject, **kwargs)
        self.target_mobject = target_mobject
        if self.target_mobject!= None:                            # Add this line in 29
            self.target_copy = self.target_mobject.copy() # Add this line in 30
        self.init_path_func()
```

**Comment by 3b1b** [comment]
In general, it should be better to use mobject1.become(mobject2) instead of that.  Is there a place where this isn't working?

As a general policy, it's now important to have as little copying done in an animation initialization as possible.  We want to make sure that copying, like that done for starting_mobject, is only done in the moment before an animation gets played, not when it's initialized.  This ensures that animations interact more nicely with each other in things like LaggedStart, AnimationGroup, and when mobject updaters are involved.  So having the "self.create_starting_mobject()" line in __init__ would create other problems down the road.

**Comment by Elteoremadebeethoven** [comment]
Perfect, I really had no knowledge of that command, thank you very much.
