### ISSUE TITLE
Where to submit documentation patches?

### ISSUE THREAD

**Issue by Kolloom** [3b1b/manim#549]
This repository does not have any more documentations other than the readme file. The readthedocs website points to eulertour's fork, which have not responded to any patches beyond october last year.

**Comment by eulertour** [comment]
Manim and documentation have had a long, troubled relationship.

**Comment by eulertour** [comment]
For a short answer, do it here. I just added the docs from my fork in 4447bbd01633eda2519b4465001ac5dc7e8f7a1d.

Manim and documentation have had a long, troubled relationship. I started writing them more or less for fun, and hosted them on a separate fork because I couldn't add webhooks to this one. And in fact, even as a collaborator I still can't add webhooks to this repo, so the best way to go is probably to update them here so I can rebase the fork.
