### ISSUE TITLE
How is this piped to ffmpeg?

### ISSUE THREAD

**Issue by jeffx99** [3b1b/manim#58]
For each scene, the frames are written as RGB data straight to stdin which gets piped to the input of ffmpeg. Is this correct? If so, then how large can the data be that is passed? Where is the data written in stdin stored? If I have 60 frames of 1920 x 1080 scenery then shouldn't that be much too large to store in RAM?

**Comment by pwaller** [comment]
(I am not affiliated with this project)

This question might be more appropriate for [stack exchange](https://unix.stackexchange.com/search?q=%5Bpipe%5D+buffer). But I'll have a quick go at an answer.

The answer to "how large is the data which can be passed" is dependent on how much input ffmpeg requires before it can start writing out frames. Once it has consumed frames it can drop them as it goes along. So ffmpeg only need "store" a rolling window of frames in RAM, probably not more than a second's worth, perhaps less. 60 frames of 1080p in RGB is only `1920*1080*3*60 ≈ 355MiB`, so buffering a second's worth is not unreasonable. The answer to "where is it stored" is "in the read or encoding buffer in ffmpeg".

You should imagine (only approximate pseudocode) in parallel:

manim side:

```
for every frame:
  stdout.write(frame)
```

ffmpeg side:

```
encoder = encode_to(stdout)
until pipe is closed:
  frame = stdin.read(size of a frame)
  encoder.encode(frame)
```

The read effectively "waits" until enough bytes have been supplied.

The language may implement some additional buffering in the "high level" read/write calls which are implemented in terms of syscalls. The encoder obviously buffers some number of frames so that it can write out a more efficient representation of a number of those frames. Once it has enough it writes to stdout.

The pipe itself actually has a buffer, too - which you can read about under [man pipe(7) "Pipe capacity"](https://linux.die.net/man/7/pipe). It's 65kiB on Linux, so only a tiny one in the context of 1080p frames.

**Comment by jeffx99** [comment]
Thanks! I meant to say 60 seconds, but you've answered my concerns.
