### ISSUE TITLE
Reason to enforce numpy 1.15?

### ISSUE THREAD

**Issue by lucasgcb** [3b1b/manim#602]
The following is locked as dependency:

https://github.com/3b1b/manim/blob/f908b68bedbc67a1ab95321252bd912f074b37d6/requirements.txt#L3

Is there a reason why the latest minor versions of numpy aren't compatible or is a PR welcome?
This is a bit odd because I do have libraries that use `>=1.16` which I'd like to utilize with manim.

**Comment by Kolloom** [comment]
My guess is that the requirements.txt is produced using `pip freeze` which defaults to exact package version https://github.com/3b1b/manim/commit/d7ed7b31962c771a11761a19baaad1ec07cabbb7#diff-b4ef698db8ca845e5845c4618278f29a

**Comment by soerface** [comment]
Personally, I made the experience that requiring "at least" instead of "exact" a version of a package, can quickly lead to failing builds because of incompatibilities. Setting a package like numpy, which has a lot of maintainers, to "at least version 1.x" instead of "exact 1.15.0" probably works out fine, but with smaller packages you get a lot of headache if you trust others blindly that they will follow semver properly. Spoiler alert: they won't.

That's why I would only used fixed version, and from time to time upgrade the dependencies. I think if you test manim with the most recent numpy version and send a PR it will be merged pretty quickly.

**Comment by eulertour** [comment]
I updated the numpy and scipy version numbers in eb13def6093ac21b939af95a4ce61ff9f88738f0.

**Comment by lucasgcb** [comment]
@eulertour I see, however the issue is about enforcing these version numbers, at least for numpy where they are fairly strict with their versioning. @ soerface gave an explanation more or less.

People using certain numerical libraries which work with the latest minor/hotfixed numpy might run into problems by trying to use manim alongside it (even though manim doesn't seem like it would break by allowing minor or patched versions so such enforcement seems needless). If it does break in a numpy patch somehow, I don't see why it can't be addressed directly instead (since those patches tend to be important).

Granted this can always be circumvented by hacking manim to use the latest version, but it's taking users into a different thing to worry about.
