### ISSUE TITLE
What is VMobject exactly?

### ISSUE THREAD

**Issue by elnurvl** [3b1b/manim#608]
Can anyone explain what is the purpose of `VMobject` and how it differs from `Mobject`?

I am trying to make some `old_projects` work. For example, I had to change `PMobject` to inherit from `VMobject` instead of `Mobject` in order to fix `NumberLineScene`. I do not know if it is correct thing to do or how will it affect the other scripts because I am unable to find the fundamental differences between the two objects. The wiki does not explain a lot, so please tell some detailed information.

I dug commit histories and saw 

> "Starting to vectorize all things"

 kind of commit messages when the `VMobject` class is added to the engine. What does it mean "Vectorize" in this context?

**Comment by Elteoremadebeethoven** [comment]
See manimlib/mobject/types/vectorized_mobject.py

**Comment by elnurvl** [comment]
I did not ask for a location of the source code. I asked for an explanation. Please read the description of the question too before replying, not only the title.

**Comment by Elteoremadebeethoven** [comment]
In that case you should understand that this is a page to expose code ISSUES, not doubts that you have about it.
That is something that you must understand on your own, no one of us will respond to you because it is a waste of time.

**Comment by elnurvl** [comment]
Then do not respond and waste my time, please.

Anyone with enough knowledge and experience on the repository will accept the thread as an ISSUE REGARDING THE DOCUMENTATION. In fact, the documentation is also a part of the repository and at the moment is quite incomplete. You must understand on your own, one does not create an ISSUE in a repository just to find a file in THAT SAME repository. Responding with an answer unrelated to the question is a much more of a time wasting rather than asking a question in the first place.

**Comment by Elteoremadebeethoven** [comment]
```Anyone with enough knowledge and experience on the repository will accept the thread as an ISSUE REGARDING THE DOCUMENTATION```,  That depends, in this case your doubt can be solved if you see the source code, which in this case is manimlib/mobject/mobject.py, manimlib/mobject/number_line.py, manimlib/mobject/types/point_cloud_mobject.py and manimlib/mobject/types/vectorized_mobject.py. 
It would not take you more than a few hours to understand it. If you ask something that is really difficult to understand or find then we would gladly help you. The problem is that you expect us to do the job that you can do with minimal effort:  ```so please tell some detailed information```.

**Comment by elnurvl** [comment]
Ridiculously you see spending few hours as a minimal effort, while you are considering to answer the question with a few sentences within few minutes as a waste of time. :) Techically, anyone can solve any issue in any open-source project by spending fair amount of time on it. But you must know what the ISSUE tab serves to in the platforms like Github before joining the conversations.

I do not ask anyone to dig the code and find an answer for me. I asked the question from the ones who ALREADY SPENT their few hours to find an answer for it or the ones who did the relevant commits in the first place. If you are not among those people, you do not have to respond to this issue, and please, do not. I do not see any productivity in this conversation since it went quite off-topic.

**Comment by Elteoremadebeethoven** [comment]
Indeed, I am one of those people who has already gone through those few hours, and I know perfectly well that with a little effort he can understand it, otherwise it would have been more specific.

If we see that it is a simple answer but long (that is this case), we simply help you to find the answer more easy. Like I did it in the first comment.

The reason why I have kept this conversation is because I want people who are going to read this to understand how GitHub works, you are a clear example of users who believe that they can learn without doing their part, since this code is very new. I can assure you that no one will answer you, because, as I said, you are the one who does not know how GitHub works.

So do not be aggressive and accept the comments that are made, it is surely for a reason.

Good luck.
