### ISSUE TITLE
why the line rotate so fast?

### ISSUE THREAD

**Issue by wsx9999** [3b1b/manim#730]
This code was modified from other's code, I want the line to rotate around the center point. But it turned faster than I expected, and I don't know what the reason is.

        from big_ol_pile_of_manim_imports import *

        class UpdateValueTracker1(Scene):
            def construct(self):
                theta=ValueTracker(PI)
                line=Line(LEFT,RIGHT)
                line.rotate(theta.get_value(),about_point=ORIGIN)
                def updater_line(obj):
                    obj.rotate(theta.get_value(),about_point=np.array([0,0,0]))
                line.add_updater(updater_line)
                self.add(line)
                self.play(theta.increment_value,PI,run_time=20)

https://youtu.be/ZnOC3_7mqEw

This is the original code

        class UpdateValueTracker1(Scene):
            def construct(self):
                theta = ValueTracker(PI/2)
                line_1= Line(ORIGIN,RIGHT*3,color=RED)
                line_2= Line(ORIGIN,RIGHT*3,color=GREEN)

                line_2.rotate(theta.get_value(),about_point=ORIGIN)

                line_2.add_updater(
                        lambda m: m.set_angle(
                                            theta.get_value()
                                        )
                    )

                self.add(line_1,line_2)

                self.play(theta.increment_value,PI/2)

                self.wait()

https://youtu.be/YuZVI0kF8zA

**Comment by zavden** [comment]
When you use an update function you have to imagine what happen every animation frame. If you think about it, each frame is rotating the value of `theta`, which in fact, is increased with the animation. That's why you notice that it moves faster and faster.
In the original code you can notice that `rotate` is not being used in the update function, but `set_angle`, that is, every moment of the animation is being set the angle` theta` to the line (which increases in the animation). So you have to use a similar method.
I must emphasize that the `set_angle` method takes as reference the initial coordinate of the line, so, this method will not works to rotate it with respect to its center.
One way to solve it is to create a copy of the initial state of the line, and rotate it taking as reference that line every moment of the animation.
```python
class RotateLine(Scene):
    def construct(self):
        theta=ValueTracker(PI)
        line=Line(LEFT,RIGHT)
        line.initial_state = line.copy()
        def updater_line(obj):
            obj.become(obj.initial_state)
            obj.rotate(theta.get_value(),about_point=np.array([0,0,0]))
        line.add_updater(updater_line)
        self.add(line)
        self.play(theta.increment_value,PI,run_time=3)
        self.wait()
```

<p align="center"><img src="https://imgur.com/ZRxLCPn.gif" width="100%"></p>

**Comment by wsx9999** [comment]
@zavden
Got it. thank you very much~

**Comment by zavden** [comment]
Please close the issue.
