### ISSUE TITLE
PiCreatures aren't showing correctly

### ISSUE THREAD

**Issue by hridoy100** [3b1b/manim#757]
### I want to show PiCreature Animation. But it's showing like this:
![NumberScene](https://user-images.githubusercontent.com/33668012/66722413-f3574580-ee2e-11e9-8510-66035b3ce1f0.gif)
Where did the circle come from?
I followed this tutorial:
[https://www.youtube.com/watch?v=KGdA8IB6JL0&t=51s](https://www.youtube.com/watch?v=KGdA8IB6JL0&t=51s)

**Comment by Elteoremadebeethoven** [comment]
That's normal, that's how I designed it so that all the scenes can be played. Since otherwise it would mark an error, because the expressions of the PiCreatures (the .svg files) are not in the repository. That video is not intended for you to use PiCreatures, but that you can play back as many scenes in old_projects as possible.

**Comment by hridoy100** [comment]
> That's normal, that's how I designed it so that all the scenes can be played. Since otherwise it would mark an error, because the expressions of the PiCreatures (the .svg files) are not in the repository. That video is not intended for you to use PiCreatures, but that you can play back as many scenes in old_projects as possible.

# Please check the youtube link again. Why is it transforming into a circle? I was using (.svg) of the symbol "Alpha".

**Comment by Elteoremadebeethoven** [comment]
You clearly did not understand me. That circle is because you followed the steps in [this video](https://youtu.be/vzyzqv8Sp8Y).
And surely, when you tried to add another expression to your AlphaCreature, since Manim didn't find the SVG, I used that circle. Make sure the expressions in your AlphaCreature are well placed, and that you have correctly modified the NumberCreature codes.
