### ISSUE TITLE
Swedish characters not working

### ISSUE THREAD

**Issue by MattesfarenNeo** [3b1b/manim#878]
Include at least:
1. Steps to reproduce the issue (e.g. the command you ran)
2. The unexpected behavior that occurred (e.g. error messages or screenshots)
3. The environment (e.g. operating system and version of manim)

I am new to manim and want to include swedish characters in a text, but it gives an error message when rendering.
Code:
class Swe(Scene):
	def construct(self):
		text = TextMobject(r"$\"o$")
		self.add(text)
		self.wait()

Error message:
Traceback (most recent call last):
  File "C:\Manim\manim\manim2020\manimlib\extract_scene.py", line 153, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Manim\manim\manim2020\manimlib\scene\scene.py", line 54, in __init__
    self.construct()
  File "Geony.py", line 115, in construct
    text = TextMobject(r"$\"o$")
  File "C:\Manim\manim\manim2020\manimlib\mobject\svg\tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "C:\Manim\manim\manim2020\manimlib\mobject\svg\tex_mobject.py", line 45, in __init__
    self.template_tex_file_body
  File "C:\Manim\manim\manim2020\manimlib\utils\tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "C:\Manim\manim\manim2020\manimlib\utils\tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: C:\Manim\manim\manim2020\manimlib\files\Tex\a26fbd67dc90adbc.log

I am running python 3.7 (64 bit) and MikTex 2.9. All other features of manim are working fine.
Any help would be much appreciated. Also, please keep in mind that I am new to manim and programing in general.

**Comment by quark67** [comment]
What Swedish character do you need? Is it ö? Depending your keyboard and settings of your operating system, you can perhaps directly enter the `ö`.  Or with `\"o` (in LaTeX, but see below for strings in Python) if you cannot enter `ö` directly. But why do you use two `$` in your try? This is for LaTeX math mode, not italic text.

So, try:
```python
text = TextMobject(r"\"o")
```

or
```python
text = TextMobject('\\"o')
``` 

(note the string in the single quote `'` in the last example, because if you use the double quote as in `"\\"o"`, the string end with the second `"`, not the third).

**Comment by MattesfarenNeo** [comment]
Thank you so much!
