### ISSUE TITLE
Exception: Latex error converting to dvi and other errors during implementing transformation

### ISSUE THREAD

**Issue by arpon113** [3b1b/manim#959]
I have tried to solve this problem by reinstalling MiKTeX and I did with complete version. I was able to run some of the animations that did not contain Tex codes. I was able to do basic Text animations and shapes animations But I was not certainly able to do anything with Latex codes, for example:
I was able to run text_1 to text_2 transformation but I wasnt even able to render any tex codes not even a png. How even I followed tutorial 4.1 transformations and I found this error when trying to animate CopyV1
`%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;F:\Matlab installation\runtime\win64;F:\Matlab installation\bin;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files (x86)\sox-14-4-2;C:\FFmpeg\bin;C:\ProgramFiles\MiKTeX\miktex\bin\x64;`

![Annotation 2020-04-05 003027](https://user-images.githubusercontent.com/53269641/78458874-83879080-76d6-11ea-90a4-53e6960e23a8.jpg)

Can you please solve it? I have tried so many times tried to replace the codes in tex_file_writing.py as some of the issue said. I hope good souls may help me.

**Comment by zavden** [comment]
Share the code

**Comment by arpon113** [comment]
> Share the code

`class CopyTextV1(Scene):
	def construct(self):
		formula = TexMobject(
			"{\\frac{d}{dx}}", #0
			"(", #1
			"u", #2
			"+", #3
			"v", #4
			")", #5
			"=", #6
			"\\frac{d}{dx}", #7
			"u", #8
			"+", #9
			"\\frac{d}{dx}", #10
			"v" #11
			)
		formula.scale(2)
		self.play(Write(formula[0:7]))
		self.wait()
		changes=[
			#Step 1
			[(2,4,3),
			(8,11,9)],
			#Step 2
			[(0,0),
			(7,10)]
		]
		for pre_ind,post_ind in changes:
			self.play(
				*[
					ReplacementTransform(formula[i].copy(),formula[j])
					for i,j in zip(pre_ind,post_ind)
				]
			)
			self(wait)
		self.wait()`

**Comment by arpon113** [comment]
> Share the code

class CopyTextV1(Scene):
	def construct(self):
		formula = TexMobject(
			"{\\frac{d}{dx}}", #0
			"(", #1
			"u", #2
			"+", #3
			"v", #4
			")", #5
			"=", #6
			"\\frac{d}{dx}", #7
			"u", #8
			"+", #9
			"\\frac{d}{dx}", #10
			"v" #11
			)
		formula.scale(2)
		self.play(Write(formula[0:7]))
		self.wait()
		changes=[
			#Step 1
			[(2,4,3),
			(8,11,9)],
			#Step 2
			[(0,0),
			(7,10)]
		]
		for pre_ind,post_ind in changes:
			self.play(
				*[
					ReplacementTransform(formula[i].copy(),formula[j])
					for i,j in zip(pre_ind,post_ind)
				]
			)
			self(wait)
		self.wait()



This is the code I am trying to render

**Comment by zavden** [comment]
Use the Markdown format to share your code, [tutorial here](https://guides.github.com/features/mastering-markdown/). The problem is not Manim, but your LaTeX code, this:
```python
"{\frac{d}{dx}}",
```
It must be:
```python
"\\frac{d}{dx}", #0
```
The original code is:
```python
class CopyTextV1(Scene):
    def construct(self):
        formula = TexMobject(
            "\\frac{d}{dx}", #0 
            "(", #1
            "u", #2
            "+", #3
            "v", #4
            ")", #5
            "=", #6
            "\\frac{d}{dx}", #7
            "u", #8
            "+", #9
            "\\frac{d}{dx}", #10
            "v" #11
            )
        formula.scale(2)
        self.play(Write(formula[0:7]))
        self.wait()
        self.play(
            ReplacementTransform(formula[2].copy(),formula[8]),
            ReplacementTransform(formula[4].copy(),formula[11]),
            ReplacementTransform(formula[3].copy(),formula[9])
            )
        self.wait()
        self.play(
            ReplacementTransform(formula[0].copy(),formula[7]),
            ReplacementTransform(formula[0].copy(),formula[10])
            )
        self.wait()
```
It is well written, so the mistake was made by you, I recommend taking a [LaTeX course](https://en.wikibooks.org/wiki/LaTeX/Mathematics), This type of error does not concern Manim, but LaTeX.

**Comment by arpon113** [comment]
I copy pasted the code but the class did not run. 

![image](https://user-images.githubusercontent.com/53269641/78462942-0b7e9200-76f9-11ea-9f43-64ba4b23ab31.png)

and I had the same error

**Comment by zavden** [comment]
Surely you wrongly edited the file tex_file_writing.py, so redownload the manim repository in another folder and run it again (you can have as many manim folders as you want). If this does not work, investigate how to correct the log that appears in your image: `latex major issue so far you have not checked for miktex updates`, I repeat, this is not a problem of Manim, but of your LaTeX distribution, so You will have to solve it on your own, since it is a very particular question. You can also see the .log file that was generated, you can see it in your image: `a4f17 .... log`.
In case you can't solve it, uninstall Miktex and install TexLive (TexLive is another LaTeX distribution).
If that doesn't work either then you can install a Linux distribution on a virtual machine (like Ubuntu, Manjaro etc) and install Manim there, Manim usually has no problem with Unix based distributions.

**Comment by arpon113** [comment]
After I editted the tex_file_writing.py I have undone the changes and saved again. I reinstalled MiKTeX. And it told me to check several manim files.
Anyways Thanks for your help :') 
I appriciate that.

**Comment by zavden** [comment]
Ok, I don't understand why you deleted your comment from my video, but ok.
