### ISSUE TITLE
Nothing happens when tried to render example_scenes.py

### ISSUE THREAD

**Issue by kaung-htet-myat** [3b1b/manim#968]
When I tried to run example_scenes.py using "python3 manim.py example_scenes.py SquareToCircle -pl", nothing happens. No error and no video shows up. I tried uninstalling and reinstalling all the packages but it happens the same.

I installed all the requirements as described in the documentation. 
- installed ffmpeg and i can call ffmpeg from the command prompt
- installed pycairo‑1.19.1‑cp37‑cp37m‑win_amd64.whl because other distributions are not compatible with my system
- installed MikTex and SoX from .exe files (did nothing after finished installing .exe files)
- and installed rest of the packages from requirement.txt file

I'm using Anaconda with python version 3.6.10.

**Comment by kettenfett** [comment]
Conda doesn't know the `python3` command, because in conda, it's always just `python`, no matter what python version you're actually running. So the commadn becomes:
`python -m manim example_scenes.py SquareToCircle -pl`

If this still not works, make sure `manim.py` is found, e.g. by explicitly passing the path to it like:
`(manim) C:\Users\username\manim-master>python -m manim example_scenes.py SquareToCircle -pl`

Also, make sure you activated your manim env.

**Comment by kaung-htet-myat** [comment]
Thanks. It worked out! I didn't notice about the anaconda environment and python3 command conflict.

**Comment by applemonkey496** [comment]
@kaung-htet-myat I'm in the same environment, and I am able run manim even without `python -m`, I simply run `manim file.py [settings]`.

**Comment by EngenMe** [comment]
same issue no fixe 
any help please
