### ISSUE TITLE
Proper Documentation?

### ISSUE THREAD

**Issue by bin0x00** [3b1b/manim#983]
When will we be able to read proper documentation, the one that already exists is very incomplete and it's timeconsuming to find all the methods and parameters of a function and class, I have tried some unofficial documentation but they are incomplete so are all tutorials? In the first place as a developer, I would look for the documentation for a code or library but I am extremely unpleased to find such crappy documentation for such a good code.

Sorry for the anger,
Dex Devlon.

**Comment by eulertour** [comment]
> Sorry for the anger

It's fine, your reaction is much better than many other people's.

It's important to keep the proper perspective on this project. It's primarily developed by a single person, for a single purpose, for use in a single development environment. And it just happens to be in a public location.

Manim doesn't have anywhere near the community support of matplotlib or numpy for example. All of the documentation, tutorials, support threads, etc. that you've come across are there because someone else was once in your position, took the time to read through the code, and wanted to make it a little easier for the next person.

The unfortunate reality is that despite producing a nice result, manim isn't designed very well. It's buggy, difficult to set up, and renders far too slowly for the average developer to use it comfortably. As a result, people tend to consider it a better use of time to try to improve the library rather than document it while it's still so unwieldy.

**Comment by bin0x00** [comment]
> The unfortunate reality is that despite producing a nice result, manim isn't designed very well. It's buggy, difficult to set up, and renders far too slowly for the average developer to use it comfortably. As a result, people tend to consider it a better use of time to try to improve the library rather than document it while it's still so unwieldy.

if I am right and not to be mean, bugs are found in any programs and fixing them is a good thing, but it doesn't even matter if no one is going to use as no one is going to understand how to do X or what does Y mean, yes I get it that there is technically only one person doing it but their cant be more people doing it as no one understands it, you may have heard that reading the documentation for 15 mins will save you googling of 2 hours.

> Manim doesn't have anywhere near the community support of matplotlib or numpy for example.

My suggestion is to make better documentation so that people don't get scared of the first look at the documentation and run away, I am sure many people world have at least looked at the repo in expectation to make some animation of there own but got scared or tired for looking for the answer. And the fact that 3b1b has over 2m subscribers also adds on to the fact.

I am again sorry to be in anger,
Dex Devlon

**Comment by eulertour** [comment]
This was resolved offline.

**Comment by bin0x00** [comment]
The conclusion of the issue for people who may have stumbled over this issue is that manim dev community is not prioritizing better documentation because of changes happening all the time and the size of the manim. Manim is not (yet) a community tool.

Correct me if I am wrong @eulertour,

Thanks,
Dex Devlon

**Comment by Shubodh** [comment]
Are there any other open-source python tools similar to Manim with better documentation?

**Comment by bin0x00** [comment]
@Shubodh, Well its complicated, you could do it the hard way using pycairo and making animation in it, or could use other libraries made on it, e.g. [mplcairo](https://github.com/matplotlib/mplcairo) which uses matplotlib on pycairo, its pretty cool but limited to mostly making graphs, other than that, I don't really know another library as complicated and well developed as pycairo, maybe processing.py might help? And just forgot to mention that manim is build on pycairo.

Thanks,
Dex Devlon

**Comment by Shubodh** [comment]
mplcairo looks interesting, will check it out. Thanks @bin0x00!
